name: "Run Systemtests"
description: "Execute System Tests"

inputs:
  shell:
    description: "The shell to use"
    required: false
    default: bash

runs:
  using: composite
  steps:
    - uses: ./operator/.github/actions/setup-java

    - uses: ./operator/.github/actions/install-core

    - uses: ./operator/.github/actions/build-operator

    - uses: ./operator/.github/actions/build-operator-image

    - name: Create k8s Kind Cluster
      uses: helm/kind-action@v1
      with:
        cluster_name: debezium-kind

    - name: Import operator image
      shell: ${{ inputs.shell }}
      run: >
        kind load docker-image quay.io/debezium/operator:nightly --name debezium-kind

    - name: Execute Systemtests
      working-directory: operator
      shell: ${{ inputs.shell }}
      run: >
        ./mvnw verify 
        -Psystemtests 
        -pl systemtests
        -Dstyle.color=always

    - name: Upload test logs
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: test-logs-${{ github.job }}
        path: |
          operator/systemtests/target/logs/**/*
