apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: config-view
rules:
  - apiGroups:
      - ""
    resources:
      - secrets
      - configmaps
    verbs:
      - get
      - list
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: debezium-operator-config-view
roleRef:
  kind: ClusterRole
  apiGroup: rbac.authorization.k8s.io
  name: config-view
subjects:
  - kind: ServiceAccount
    name: debezium-operator