debezium.server.image.name=quay.io/debezium/server
quarkus.application.name=debezium-operator


# Quarkus helm configurations
quarkus.helm.values."app.envs.QUARKUS_OPERATOR_SDK_CONTROLLERS_DEBEZIUMSERVER_NAMESPACES".value=JOSDK_ALL_NAMESPACES