name: "Maven build core dependencies"
description: "Maven build core dependencies from Debezium"

inputs:
  shell:
    description: "The shell to use"
    required: false
    default: bash

runs:
  using: composite
  steps:
    - name: Check if pull request branch exists in debezium main repository
      id: branch
      env:
        branch_name: ${{ github.head_ref }}
      shell: ${{ inputs.shell }}
      run: |
        curl --silent -X "GET" https://api.github.com/repos/debezium/debezium/pulls | jq '.[] | {branch: .head.ref}' | jq -r '.branch' >> SORTED_PULLS.txt

        while IFS=" " read -r BRANCH;
        do
          if grep -q "$branch_name" <<< "$BRANCH"; then
            echo "BRANCH_FOUND=true" >> $GITHUB_OUTPUT
          fi
        done < SORTED_PULLS.txt

    - name: Checkout core repository with pull request branch
      if: ${{ steps.branch.outputs.BRANCH_FOUND == 'true' }}
      uses: actions/checkout@v4
      with:
        repository: ${{ github.event.pull_request.user.login }}/debezium
        ref: ${{ github.head_ref }}
        path: core

    - name: Checkout core repository with default base branch
      if: ${{ steps.branch.outputs.BRANCH_FOUND != 'true' }}
      uses: actions/checkout@v4
      with:
        repository: debezium/debezium
        ref: ${{ github.base_ref }}
        path: core

    - name: Checkout Debezium Operator
      uses: actions/checkout@v4
      with:
        path: operator

    - uses: ./operator/.github/actions/setup-java

    - name: Maven build core dependencies
      shell: ${{ inputs.shell }}
      run: >
        ./operator/mvnw clean install -f core/pom.xml 
        -DskipTests 
        -DskipITs 
        -Dformat.formatter.goal=validate
        -Dformat.imports.goal=check 
        -Dhttp.keepAlive=false 
        -Dmaven.wagon.http.pool=false
        -Dmaven.wagon.httpconnectionManager.ttlSeconds=120
        -Dmaven.javadoc.skip=true 
        -Dstyle.color=always 
        --no-transfer-progress
        -T4